#!/usr/bin/env python3
"""Regenerate the decdn_node role's network profiles from upstream deployment manifests.

    scripts/sync-network-profiles.py <path-to-decdn-checkout> [--ref origin/main] [--check]

Writes ansible/roles/decdn_node/vars/main/networks.yml: one entry per chain upstream's
`decdn config init --chain <name>` knows, holding the contract addresses that command
would bake into node.toml. Operators then set `decdn_network: <name>` instead of
hand-copying eight addresses that change wholesale on every upstream redeploy.

Everything is read from git at --ref (default origin/main), never from the working
tree, so a checkout sitting on a feature branch still yields main's deployment. Two
upstream files are the source:

  crates/cli/src/known_chains.rs     the KNOWN_CHAINS registry: name + chain_id
  contracts/deployments/<id>.json    that chain's manifest (the CLI embeds a
                                     byte-identical copy under crates/cli/deployments/)

The manifest-key -> node.toml-key mapping below mirrors KnownChain::addresses() in
known_chains.rs. Keep the two in step if upstream adds an address.

--check regenerates in memory and exits 1 if the committed file differs (CI drift
check; the header's commit line is ignored so an unrelated upstream commit is not
drift).
"""

import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
OUT = REPO / "ansible/roles/decdn_node/vars/main/networks.yml"

# decdn_node variable suffix -> where KnownChain::addresses() reads it.
CONTRACTS = [
    ("payment_pool_address", "PaymentPool"),
    ("capacity_bond_address", "CapacityBond"),
    ("slash_judge_address", "SlashJudge"),
    ("content_blacklist_address", "ContentBlacklist"),
    ("slash_appeal_address", "SlashAppeal"),
    ("origin_assignment_address", "OriginAssignment"),
    ("publisher_registry_address", "PublisherRegistry"),
]
EXTERNAL = [("usdc_address", "usdc")]

ADDRESS = re.compile(r"^0x[0-9a-fA-F]{40}$")
# One KnownChain { ... } literal: its name and chain_id (Rust allows `421_614`).
CHAIN = re.compile(
    r"KnownChain\s*\{[^}]*?\bname:\s*\"(?P<name>[a-z0-9-]+)\"[^}]*?\bchain_id:\s*(?P<id>[0-9_]+)",
    re.S,
)


def git(upstream: Path, *args: str) -> str:
    return subprocess.run(
        ["git", "-C", str(upstream), *args], check=True, capture_output=True, text=True
    ).stdout


def render(upstream: Path, ref: str) -> str:
    commit = git(upstream, "rev-parse", ref).strip()
    registry = git(upstream, "show", f"{ref}:crates/cli/src/known_chains.rs")
    chains = [(m["name"], int(m["id"].replace("_", ""))) for m in CHAIN.finditer(registry)]
    if not chains:
        sys.exit(f"no KnownChain entries parsed from known_chains.rs at {ref}")

    lines = [
        "---",
        "# GENERATED by scripts/sync-network-profiles.py -- do not hand-edit.",
        f"# Source: decdn/decdn @ {commit}",
        "#   crates/cli/src/known_chains.rs (KNOWN_CHAINS) + contracts/deployments/<chainId>.json",
        "#",
        "# The addresses `decdn config init --chain <name>` bakes into node.toml. The role's",
        "# address defaults read this map lazily when decdn_network is set, so an explicit",
        "# inventory value still wins. Protocol facts: upstream's deployment manifests are",
        "# the source, this file only mirrors them.",
        "_decdn_network_profiles:",
    ]
    for name, chain_id in chains:
        manifest = json.loads(git(upstream, "show", f"{ref}:contracts/deployments/{chain_id}.json"))
        if manifest.get("chainId") != chain_id:
            sys.exit(f"{chain_id}.json chainId {manifest.get('chainId')} != registry {chain_id} for {name}")
        values = []
        for var, key in CONTRACTS:
            values.append((var, manifest["contracts"].get(key)))
        for var, key in EXTERNAL:
            values.append((var, manifest["externalDeps"].get(key)))
        for var, value in values:
            if not isinstance(value, str) or not ADDRESS.match(value):
                sys.exit(f"{name}: {var} is {value!r} in {chain_id}.json, not a 0x address")
        lines += [f"  {name}:", f"    chain_id: {chain_id}"]
        lines += [f'    {var}: "{value}"' for var, value in values]
        lines += [f"    deploy_block: {int(manifest['deployBlock'])}"]
    return "\n".join(lines) + "\n"


def strip_commit(text: str) -> str:
    return re.sub(r"^# Source: .*$", "", text, flags=re.M)


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("upstream", type=Path, help="path to a decdn/decdn git checkout")
    ap.add_argument("--ref", default="origin/main", help="git ref to read (default: origin/main)")
    ap.add_argument("--check", action="store_true", help="exit 1 if the committed file is stale")
    args = ap.parse_args()

    text = render(args.upstream, args.ref)
    if args.check:
        current = OUT.read_text() if OUT.exists() else ""
        if strip_commit(current) != strip_commit(text):
            sys.exit(f"{OUT.relative_to(REPO)} is stale against {args.ref}; re-run without --check")
        print(f"{OUT.relative_to(REPO)} is current against {args.ref}")
        return
    OUT.write_text(text)
    print(f"wrote {OUT.relative_to(REPO)}")


if __name__ == "__main__":
    main()
