#!/usr/bin/env bash
# Vendor upstream's Grafana dashboards and Prometheus alert rules into the chart.
#
#   scripts/sync-monitoring.sh <path-to-decdn-checkout> [ref] [--check]
#
# Copies decdn/decdn's monitoring/*.json and monitoring/prometheus-alerts.yml at
# <ref> (default origin/main, read with `git show`, never from the working tree)
# into charts/decdn-node/files/monitoring/, and records the upstream commit plus a
# sha256 per file in SOURCE. The chart renders them as a PrometheusRule and Grafana
# dashboard ConfigMaps; Ansible/Grafana Cloud users import the same files by hand
# (see that directory's README.md).
#
# --check copies into a scratch dir instead and exits 1 when the vendored files
# differ from <ref> (the commit line in SOURCE is ignored, so an unrelated upstream
# commit is not drift).
set -euo pipefail

usage() { echo "usage: $0 <decdn-checkout> [ref] [--check]" >&2; exit 2; }

upstream="" ref="origin/main" check=false
for arg in "$@"; do
  case "$arg" in
    --check) check=true ;;
    -*) usage ;;
    *) if [[ -z "$upstream" ]]; then upstream="$arg"; else ref="$arg"; fi ;;
  esac
done
[[ -n "$upstream" ]] || usage

repo="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
dest="$repo/charts/decdn-node/files/monitoring"

commit="$(git -C "$upstream" rev-parse --verify "$ref^{commit}")"
mapfile -t files < <(git -C "$upstream" ls-tree --name-only "$ref" monitoring/ \
  | grep -E '^monitoring/[^/]+\.(json|ya?ml)$' | sort)
((${#files[@]} > 0)) || { echo "no monitoring files at $ref" >&2; exit 1; }

out="$dest"
if $check; then
  out="$(mktemp -d)"
  trap 'rm -rf "$out"' EXIT
fi
mkdir -p "$out"

{
  echo "# GENERATED by scripts/sync-monitoring.sh -- do not hand-edit."
  echo "upstream: decdn/decdn"
  echo "commit: $commit"
  echo "files:"
} > "$out/SOURCE"
for f in "${files[@]}"; do
  name="$(basename "$f")"
  git -C "$upstream" show "$ref:$f" > "$out/$name"
  echo "  $name: sha256:$(sha256sum "$out/$name" | cut -d' ' -f1)" >> "$out/SOURCE"
done

if $check; then
  # Vendored files present locally but gone upstream count as drift too.
  stale=0
  for f in "$dest"/*.json "$dest"/*.yml "$dest"/*.yaml; do
    [[ -e "$f" ]] || continue
    [[ -e "$out/$(basename "$f")" ]] || { echo "removed upstream: $(basename "$f")"; stale=1; }
  done
  if ! diff -q <(grep -v '^commit:' "$dest/SOURCE") <(grep -v '^commit:' "$out/SOURCE") >/dev/null; then
    diff <(grep -v '^commit:' "$dest/SOURCE") <(grep -v '^commit:' "$out/SOURCE") || true
    stale=1
  fi
  if ((stale)); then
    echo "charts/decdn-node/files/monitoring is stale against $ref; re-run without --check" >&2
    exit 1
  fi
  echo "charts/decdn-node/files/monitoring is current against $ref"
  exit 0
fi

# Drop vendored files that upstream removed.
for f in "$dest"/*.json "$dest"/*.yml "$dest"/*.yaml; do
  [[ -e "$f" ]] || continue
  printf '%s\n' "${files[@]}" | grep -qx "monitoring/$(basename "$f")" || rm -f -- "$f"
done
echo "vendored ${#files[@]} files from decdn/decdn@${commit:0:12} into charts/decdn-node/files/monitoring"
